name: lifecoach
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  widgets:
    path: ./packages/widgets

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - res/images/onboarding_guy.png
    - res/images/onboarding.jpeg

  fonts:
    - family: Varela Round
      fonts:
        - asset: res/fonts/VarelaRound-Regular.ttf

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "res/logo/foreground.png"

  android: true
  adaptive_icon_background: "#EEEEEE"
  adaptive_icon_foreground: "res/logo/foreground_old.png"
  min_sdk_android: 23

  ios: true
  remove_alpha_ios: true
  background_color_ios: "#EEEEEE"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#EEEEEE"
  image: res/logo/foreground_old.png